### ISSUE TITLE
A vulnerability in type()

### ISSUE THREAD

**Issue by xiaofen9** [sindresorhus/component-type#25]
We found that a maliciously crafted user-input object can type detection result of component-type module. The vulnerability is from the following code: component-type leverages the _isBuffer property from unsafe user-input to detect buffer type information. However, a crafted payload can overwrite this property to manipulate the type detection result.

https://github.com/component/type/blob/a581cc14d0b46b8a4c96e2fc99fa76cd7faef5d9/index.js#L39-L46

Reproduce Script
```
var type = require('component-type');

var json = {
    "key": "OK",
    "_isBuffer":1
};

function test(userJson){
   return type(userJson);
}
console.log(test(json));
```

**Comment by sindresorhus** [comment]
This was fixed at some point. It's not a vulnerability. Just a bug.
