### ISSUE TITLE
Another vulnerability in type() API

### ISSUE THREAD

**Issue by xiaofen9** [sindresorhus/component-type#26]
Another vul similar to https://github.com/component/type/issues/25 is found in component-type. A crafted payload can forge an internal property (nodeType) to manipulate the type detection result.

```
var type = require('component-type');

var json = {
    "key": "OK",
    "nodeType":1
};

function test(userJson){
   return type(userJson);
}
console.log(test(json));

```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/component-type/pull/27#issuecomment-1815275128
